version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    container_name: ${PROJECT_NAME}_wordpress
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DATABASE}
      WORDPRESS_DEBUG: true
    volumes:
      - ./wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes

  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_DATABASE: ${WP_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - wp_db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PROJECT_NAME}_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${WP_DB_PORT}:80"

volumes:
  wp_db:
